## Imports

In [1]:
import pandas
import numpy
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
import mysql.connector
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error
import joblib
import datetime
import statsmodels
%matplotlib qt

In [2]:
with open('../config.env') as f:
    credentials=f.read()
credentials=credentials.split(" ")
con = mysql.connector.connect(username=credentials[0],password=credentials[1],host=credentials[2],port=credentials[3],database=credentials[4])
query=con.cursor()



In [3]:
sql="SELECT * FROM total_india_cases"
query.execute(sql)
result=query.fetchall()
column=[columns[0] for columns in query.description]

In [4]:
data=pandas.DataFrame(result,columns=column)

In [5]:
# data

In [6]:
# data.info()

In [7]:
# data.describe()

In [8]:
# data.plot(kind='line',x='date',y='total_confirmed',figsize=(20,15))

In [9]:
# data.plot(kind='line',x='date',y='total_active',figsize=(20,15))

In [10]:
# data.plot(kind='line',x='date',y='delta_active',figsize=(20,15))

In [11]:
# data.plot(kind='line',x='date',y=['total_confirmed','total_active','total_tested'],figsize=(20,15))

In [12]:
# data.plot(kind='line',x='date',y=['delta_confirmed','delta_active','delta_tested'],figsize=(20,15))

In [13]:
# data.plot(kind='line',x='date',y=['delta7_confirmed','delta7_active','delta7_tested'],figsize=(20,15))

In [14]:
# data.corr()

In [15]:
def splitting(data,training_ratio):
    length=len(data)
    traing_indexes=int(length*training_ratio)
    training_set=data[:traing_indexes]
    testing_set=data[traing_indexes:]
    return training_set,testing_set

In [16]:
training_data,testing_data=splitting(data,0.9)

In [17]:
len(training_data)

506

In [18]:
len(testing_data)

57

In [19]:
# training_data.value_counts()

In [20]:
# testing_data.value_counts()

In [21]:
features_data=training_data[['ordinal_date']]

In [22]:
# features_data

In [23]:
labels=training_data['total_confirmed']

In [24]:
# labels

In [25]:
features=features_data.to_numpy()

In [26]:
# features

# model implementation

In [27]:
model=LinearRegression()

In [28]:
model.fit(features,labels)

LinearRegression()

In [29]:
model.predict([[737987]])

array([23878880.2206955])

In [30]:
train_predicted=model.predict(features)

In [31]:
test_features=testing_data[['ordinal_date']].to_numpy()

In [32]:
test_labels=testing_data['total_confirmed']

In [33]:
test_predicted=model.predict(test_features)

In [34]:
train_predicted

array([-7054633.67407227, -6880523.83976746, -6822487.22833252,
       -6184084.50254822, -5197462.10816193, -5139425.49672699,
       -5081388.88529205, -5023352.27385712, -4965315.66242218,
       -4907279.05098724, -4849242.43955231, -4791205.82811737,
       -4733169.21668243, -4675132.6052475 , -4617095.99381256,
       -4559059.38237762, -4501022.77094269, -4442986.15950775,
       -4384949.54807281, -4326912.93663788, -4268876.32520294,
       -4210839.71376801, -4152803.10233307, -4094766.49089813,
       -4036729.8794632 , -3978693.26802826, -3920656.65659332,
       -3862620.04515839, -3804583.43372345, -3746546.82228851,
       -3688510.21085358, -3630473.59941864, -3572436.9879837 ,
       -3514400.37654877, -3456363.76511383, -3398327.15367889,
       -3340290.54224396, -3282253.93080902, -3224217.31937408,
       -3166180.70793915, -3108144.09650421, -3050107.48506927,
       -2992070.87363434, -2934034.2621994 , -2875997.65076447,
       -2817961.03932953, -2759924.42789

In [35]:
test_predicted

array([23936916.83213043, 23994953.44356537, 24052990.05500031,
       24111026.66643524, 24169063.27787018, 24227099.88930511,
       24285136.50074005, 24343173.11217499, 24401209.72360992,
       24459246.33504486, 24517282.9464798 , 24575319.55791473,
       24633356.16934967, 24691392.78078461, 24749429.39221954,
       24807466.00365448, 24865502.61508942, 24923539.22652435,
       24981575.83795929, 25039612.44939423, 25097649.06082916,
       25155685.6722641 , 25213722.28369904, 25271758.89513397,
       25329795.50656891, 25387832.11800385, 25445868.72943878,
       25503905.34087372, 25561941.95230865, 25619978.56374359,
       25678015.17517853, 25736051.78661346, 25794088.3980484 ,
       25852125.00948334, 25910161.62091827, 25968198.23235321,
       26026234.84378815, 26084271.45522308, 26142308.06665802,
       26200344.67809296, 26258381.28952789, 26316417.90096283,
       26374454.51239777, 26432491.1238327 , 26490527.73526764,
       26548564.34670258, 26606600.95812

In [36]:
# plt.plot(predicted,test_features)

In [37]:
# plt.plot(test_features,predicted)

## Evaluation

In [39]:
mean_squared_error_evaluation=mean_squared_error(test_labels,test_predicted)
mean_absolute_error_evaluation=mean_absolute_error(test_labels,test_predicted)

In [40]:
mean_squared_error_evaluation

43831974439937.06

In [41]:
numpy.sqrt(mean_squared_error_evaluation)

6620572.062891322

In [42]:
mean_absolute_error_evaluation

6612273.626640186

In [43]:
def returnNext7days():
    date=738044
    date_range=[]
    l=[]
    for i in range(1,8):
        l.append([date+i])
        date_range.append(datetime.date.fromordinal(date+i))
    return l,date_range
predictingdate,daterange=returnNext7days()
print(predictingdate)
print(daterange)

[[738045], [738046], [738047], [738048], [738049], [738050], [738051]]
[datetime.date(2021, 9, 12), datetime.date(2021, 9, 13), datetime.date(2021, 9, 14), datetime.date(2021, 9, 15), datetime.date(2021, 9, 16), datetime.date(2021, 9, 17), datetime.date(2021, 9, 18)]


In [63]:
next7days_predicted=model.predict(predictingdate)

NameError: name 'predictingdate' is not defined

In [45]:
next7days_predicted

array([27245003.68391418, 27303040.29534912, 27361076.90678406,
       27419113.51821899, 27477150.12965393, 27535186.74108887,
       27593223.3525238 ])

## forcasting the results for next 7 days

In [46]:
plt.plot(data['date'],numpy.concatenate((train_predicted,test_predicted)),label='Line of Regression')
plt.plot(data['date'],numpy.concatenate((labels,test_labels)),label='Acual Data')
plt.plot(daterange,next7days_predicted)
plt.legend()
plt.show()

## Forcasting tecnique