## Imports

In [1]:
import pandas
import numpy
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
import mysql.connector
from sklearn.linear_model import LinearRegression,Lasso
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor,ExtraTreeRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,mean_squared_log_error
import joblib
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.neural_network import MLPRegressor

In [2]:
with open('../config.env') as f:
    credentials=f.read()
credentials=credentials.split(" ")
con = mysql.connector.connect(username=credentials[0],password=credentials[1],host=credentials[2],port=credentials[3],database=credentials[4])
query=con.cursor()

In [3]:
sql="SELECT * FROM total_india_cases"
query.execute(sql)
result=query.fetchall()
column=[columns[0] for columns in query.description]

In [4]:
data=pandas.DataFrame(result,columns=column)

In [5]:
# data

In [6]:
# data=data[520:]

In [7]:
# %matplotlib qt
%matplotlib inline

In [8]:
# data.plot(kind='scatter',x='date',y='total_confirmed',figsize=(20,15))

In [9]:
# data.plot(kind='line',x='date',y=['total_confirmed','total_active','total_recovered'],figsize=(20,15))

In [10]:
# data.plot(kind='line',x='date',y=['delta_confirmed','delta_active','delta_recovered'],figsize=(20,15))

In [11]:
# data.plot(kind='line',x='date',y=['delta7_confirmed','delta7_active','delta7_recovered'],figsize=(20,15))

### Train Test Splitting

In [12]:
train_data,test_data=train_test_split(data,train_size=0.99,shuffle=False)

In [13]:
# train_data

In [14]:
# test_data

In [15]:
train_features1=train_data[['ordinal_date']].to_numpy()

In [16]:
train_features2=train_data[['ordinal_date','delta_tested']].to_numpy()

In [17]:
train_features3=train_data[['ordinal_date','delta_tested','delta_recovered']].to_numpy()

In [18]:
train_labels=train_data['delta_confirmed']

In [19]:
# train_labels

In [20]:
test_features1=test_data[['ordinal_date']].to_numpy()

In [21]:
test_features2=test_data[['ordinal_date','delta_tested']].to_numpy()

In [22]:
test_features3=test_data[['ordinal_date','delta_tested','delta_recovered']].to_numpy()

In [23]:
test_labels=test_data['delta_confirmed']

In [24]:
# test_labels

## Model selection

In [25]:
model1=RandomForestRegressor(n_estimators=1000,random_state=42,min_samples_split=5)
model2=DecisionTreeRegressor()
model3=ExtraTreeRegressor()

In [26]:
model1.fit(train_features1,train_labels)

RandomForestRegressor(min_samples_split=5, n_estimators=1000, random_state=42)

In [27]:
train_data_predicted1=model1.predict(train_features1)

In [28]:
train_data_predicted1

array([1.05988687e+00, 1.05988687e+00, 1.05988687e+00, 1.03675354e+00,
       2.64327540e+00, 2.64161825e+00, 1.33994548e+01, 6.55999971e+00,
       3.54202987e+00, 3.49613146e+00, 4.43616717e+00, 9.03598066e+00,
       1.13574183e+01, 1.02381752e+01, 1.03136648e+01, 1.04297993e+01,
       1.04326064e+01, 1.07928782e+01, 1.39982052e+01, 2.07474217e+01,
       2.40120992e+01, 2.80246199e+01, 5.15324108e+01, 7.21390851e+01,
       7.64741803e+01, 8.09801442e+01, 8.10355644e+01, 8.23360799e+01,
       8.81210803e+01, 1.33140544e+02, 1.46662242e+02, 1.52994795e+02,
       1.76653745e+02, 2.85686389e+02, 3.96449409e+02, 4.77488683e+02,
       5.40560529e+02, 5.55121882e+02, 5.55717847e+02, 5.45817293e+02,
       5.50604454e+02, 5.76862680e+02, 7.58752952e+02, 8.21965791e+02,
       8.35961963e+02, 8.56620834e+02, 1.01293244e+03, 1.00988752e+03,
       1.01349628e+03, 1.02655083e+03, 1.05549254e+03, 1.29216138e+03,
       1.39727961e+03, 1.39434445e+03, 1.43840010e+03, 1.44197302e+03,
      

In [29]:
train_labels

0          1
1          1
2          1
3          0
4          2
       ...  
574    31411
575    29565
576    28169
577    26999
578    14907
Name: delta_confirmed, Length: 579, dtype: int64

In [30]:
mean_absolute_error(train_labels,train_data_predicted1)

1903.7622044692089

In [31]:
numpy.sqrt(mean_squared_error(train_labels,train_data_predicted1))

3470.088726159209

In [32]:
mean_squared_log_error(train_labels,train_data_predicted1)

0.009083379984322472

In [33]:
r2_score(train_labels,train_data_predicted1)

0.9981650224149302

In [34]:
test_data_predicted1=model1.predict(test_features1)

In [35]:
test_data_predicted1

array([20010.87417989, 20010.87417989, 20010.87417989, 20010.87417989,
       20010.87417989, 20010.87417989])

In [36]:
test_labels

579    21898
580    23166
581    27285
582    23918
583    23189
584    21644
Name: delta_confirmed, dtype: int64

In [37]:
mean_absolute_error(test_labels,test_data_predicted1)

3505.792486779896

In [76]:
# model2.fit(train_features1,train_labels)
model3.fit(train_features1,train_labels)

ExtraTreeRegressor()

In [77]:
# train_data_predicted2=model2.predict(train_features1)
train_data_predicted2=model3.predict(train_features1)

In [40]:
train_data_predicted2

array([1.00000e+00, 1.00000e+00, 1.00000e+00, 0.00000e+00, 2.00000e+00,
       1.00000e+00, 2.20000e+01, 2.00000e+00, 1.00000e+00, 3.00000e+00,
       5.00000e+00, 9.00000e+00, 1.50000e+01, 8.00000e+00, 1.00000e+01,
       1.00000e+01, 1.10000e+01, 1.00000e+01, 1.40000e+01, 2.00000e+01,
       2.50000e+01, 2.70000e+01, 5.80000e+01, 7.80000e+01, 6.90000e+01,
       9.40000e+01, 7.40000e+01, 8.60000e+01, 7.30000e+01, 1.53000e+02,
       1.36000e+02, 1.20000e+02, 1.87000e+02, 3.09000e+02, 4.24000e+02,
       4.86000e+02, 5.60000e+02, 5.79000e+02, 6.09000e+02, 4.84000e+02,
       5.73000e+02, 5.65000e+02, 8.13000e+02, 8.71000e+02, 8.54000e+02,
       7.58000e+02, 1.24300e+03, 1.03100e+03, 8.86000e+02, 1.06100e+03,
       9.22000e+02, 1.37100e+03, 1.58000e+03, 1.23900e+03, 1.53700e+03,
       1.29200e+03, 1.66700e+03, 1.40800e+03, 1.83500e+03, 1.60700e+03,
       1.56800e+03, 1.90200e+03, 1.70500e+03, 1.80200e+03, 2.39600e+03,
       2.56400e+03, 2.95200e+03, 3.65600e+03, 2.97100e+03, 3.602

In [78]:
mean_absolute_error(train_labels,train_data_predicted2
                   )

0.0

In [79]:
test_data_predicted2=model3.predict(test_features1)

In [80]:
mean_absolute_error(test_labels,test_data_predicted2)

8609.666666666666

In [81]:
model3.predict(test_features1)

array([14907., 14907., 14907., 14907., 14907., 14907.])

In [ ]:
svmmodel=svm.SVR(kernel='rbf', C=10, gamma=0.1, epsilon=.1)
svmmodel=svm.SVR(kernel='poly', C=10, gamma='auto', degree=2,coef0=1)

In [ ]:
svmmodel.fit(train_features1,train_labels)

In [ ]:
svmmodel.predict(train_features1)

In [ ]:
mean_absolute_error(train_labels,svmmodel.predict(train_features1))

In [48]:
lassomodel=Lasso()

In [49]:
lassomodel.fit(train_features1,train_labels)

Lasso()

In [50]:
lassomodel.predict(train_features1)

array([  4619.04287155,   5126.30660729,   5295.39451921,   7155.36155029,
        10029.85605288,  10198.94396479,  10368.03187671,  10537.11978863,
        10706.20770055,  10875.29561245,  11044.38352437,  11213.47143629,
        11382.55934821,  11551.64726013,  11720.73517205,  11889.82308397,
        12058.91099587,  12227.99890779,  12397.08681971,  12566.17473163,
        12735.26264355,  12904.35055546,  13073.43846738,  13242.52637929,
        13411.61429121,  13580.70220312,  13749.79011504,  13918.87802696,
        14087.96593888,  14257.0538508 ,  14426.1417627 ,  14595.22967462,
        14764.31758654,  14933.40549846,  15102.49341038,  15271.5813223 ,
        15440.66923422,  15609.75714612,  15778.84505804,  15947.93296996,
        16117.02088188,  16286.1087938 ,  16455.19670571,  16624.28461763,
        16793.37252954,  16962.46044146,  17131.54835337,  17300.63626529,
        17469.72417721,  17638.81208913,  17807.90000105,  17976.98791297,
        18146.07582487,  

In [51]:
mean_absolute_error(train_labels,lassomodel.predict(train_features1))

47976.48680444705

In [52]:
nnregrassion=MLPRegressor(alpha=0.1)

In [53]:
nnregrassion.fit(train_features1,train_labels)

MLPRegressor(alpha=0.1)

In [54]:
nnregrassion.predict(train_features1)

array([58808.91938115, 58809.1586187 , 58809.23836456, 58810.11556893,
       58811.47124843, 58811.55099428, 58811.63074013, 58811.71048598,
       58811.79023184, 58811.86997769, 58811.94972354, 58812.02946939,
       58812.10921525, 58812.1889611 , 58812.26870695, 58812.3484528 ,
       58812.42819866, 58812.50794451, 58812.58769036, 58812.66743621,
       58812.74718207, 58812.82692792, 58812.90667377, 58812.98641962,
       58813.06616548, 58813.14591133, 58813.22565718, 58813.30540303,
       58813.38514889, 58813.46489474, 58813.54464059, 58813.62438644,
       58813.7041323 , 58813.78387815, 58813.863624  , 58813.94336985,
       58814.02311571, 58814.10286156, 58814.18260741, 58814.26235326,
       58814.34209912, 58814.42184497, 58814.50159082, 58814.58133667,
       58814.66108253, 58814.74082838, 58814.82057423, 58814.90032008,
       58814.98006594, 58815.05981179, 58815.13955764, 58815.21930349,
       58815.29904935, 58815.3787952 , 58815.45854105, 58815.5382869 ,
      

In [55]:
mean_absolute_error(train_labels,nnregrassion.predict(train_features1))

49810.16813827238

In [56]:
from sklearn.linear_model import Ridge

In [57]:
ridgemodel=Ridge()

In [58]:
ridgemodel.fit(train_features1,train_labels)

Ridge()

In [59]:
ridgemodel.predict(train_features1)

array([  4619.03487088,   5126.29868239,   5295.38661955,   7155.3539284 ,
        10029.84886028,  10198.93679744,  10368.02473462,  10537.11267178,
        10706.20060895,  10875.28854612,  11044.37648329,  11213.46442045,
        11382.55235763,  11551.64029479,  11720.72823195,  11889.81616913,
        12058.90410629,  12227.99204347,  12397.07998063,  12566.1679178 ,
        12735.25585496,  12904.34379214,  13073.4317293 ,  13242.51966648,
        13411.60760364,  13580.69554082,  13749.78347798,  13918.87141515,
        14087.95935231,  14257.04728949,  14426.13522665,  14595.22316383,
        14764.31110099,  14933.39903817,  15102.48697533,  15271.5749125 ,
        15440.66284966,  15609.75078684,  15778.838724  ,  15947.92666118,
        16117.01459834,  16286.10253552,  16455.19047268,  16624.27840985,
        16793.36634701,  16962.45428419,  17131.54222135,  17300.63015851,
        17469.71809569,  17638.80603285,  17807.89397003,  17976.98190719,
        18146.06984437,  

In [60]:
mean_absolute_error(train_labels,train_features1)

679578.9585492228

In [61]:
from sklearn.neighbors import KNeighborsRegressor

In [62]:
knnregression=KNeighborsRegressor()

In [63]:
knnregression.fit(train_features1,train_labels)

KNeighborsRegressor()

In [64]:
knnregression.predict(train_features1)

array([1.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00,
       5.600000e+00, 5.600000e+00, 5.600000e+00, 5.800000e+00,
       6.600000e+00, 4.000000e+00, 6.600000e+00, 8.000000e+00,
       9.400000e+00, 1.040000e+01, 1.080000e+01, 9.800000e+00,
       1.100000e+01, 1.300000e+01, 1.600000e+01, 1.920000e+01,
       2.880000e+01, 4.160000e+01, 5.140000e+01, 6.520000e+01,
       7.460000e+01, 8.020000e+01, 7.920000e+01, 9.600000e+01,
       1.044000e+02, 1.136000e+02, 1.338000e+02, 1.810000e+02,
       2.352000e+02, 3.052000e+02, 3.932000e+02, 4.716000e+02,
       5.316000e+02, 5.436000e+02, 5.610000e+02, 5.620000e+02,
       6.088000e+02, 6.612000e+02, 7.352000e+02, 7.722000e+02,
       9.078000e+02, 9.514000e+02, 9.544000e+02, 9.958000e+02,
       1.028600e+03, 1.054200e+03, 1.164000e+03, 1.234600e+03,
       1.329800e+03, 1.403800e+03, 1.463000e+03, 1.428600e+03,
       1.547800e+03, 1.561800e+03, 1.617000e+03, 1.664000e+03,
       1.723400e+03, 1.716800e+03, 1.874600e+03, 2.0738

In [65]:
mean_absolute_error(train_labels,knnregression.predict(train_features1))

2598.4642487046635

In [66]:
knnregression.predict(test_features1)

array([26210.2, 26210.2, 26210.2, 26210.2, 26210.2, 26210.2])

In [67]:
# model1.fit(train_features2,train_labels)

In [68]:
# train_data_predicted2=model1.predict(train_features2)

In [69]:
# train_data_predicted2

In [70]:
# train_labels

In [71]:
# mean_absolute_error(train_labels,train_data_predicted2)

In [72]:
# numpy.sqrt(mean_squared_error(train_labels,train_data_predicted2))

In [73]:
# mean_squared_log_error(train_labels,train_data_predicted2)

In [74]:
# r2_score(train_labels,train_data_predicted2)